USE [SIS_Activity]
GO

/****** Object:  StoredProcedure [dbo].[CREATE_ACTIVITY]    Script Date: 28/06/2023 12:58:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[CREATE_ACTIVITY](@JSON NVARCHAR(MAX))
AS
BEGIN

	--START -> DECLARING VARIABLES
	DECLARE @TR_CREATE_ACTIVITY NVARCHAR(MAX)
	DECLARE @ACTIVEORGANIZERS NVARCHAR(MAX)
	DECLARE @ACTIVITYINFORMATION NVARCHAR(MAX)
	DECLARE @AVAILABLECDS NVARCHAR(MAX)
	DECLARE @DETAILSOFSUSPECT NVARCHAR(MAX)
	DECLARE @DETAILSOFINSTRUCTORS NVARCHAR(MAX)
	DECLARE @DETAILSOFLOCALCONTACTS NVARCHAR(MAX)
	DECLARE @DETAILSOFVICTIMS NVARCHAR(MAX)
	DECLARE @FILEREFERENCES NVARCHAR(MAX)
	DECLARE @INCIDENTS NVARCHAR(MAX)
	DECLARE @INSTITUTIONSAFFECTED NVARCHAR(MAX)
	DECLARE @ITEMSDISMISS NVARCHAR(MAX)
	DECLARE @ITEMSUSED NVARCHAR(MAX)
	DECLARE @MAINSPEAKERS NVARCHAR(MAX)
	DECLARE @MODUSOPERANDI NVARCHAR(MAX)
	DECLARE @NARRATIVEINFORMATION NVARCHAR(MAX)
	DECLARE @NOOFINSTRUCTORS NVARCHAR(MAX)
	DECLARE @NOOFPERSONSPARTICIPATED NVARCHAR(MAX)
	DECLARE @NOOFVICTIMS NVARCHAR(MAX)
	DECLARE @PHOTOGRAPHS NVARCHAR(MAX)
	DECLARE @PRESIDEDOVERBY NVARCHAR(MAX)
	DECLARE @RELATEDACTIVITIES NVARCHAR(MAX)
	DECLARE @RELATEDACTIVITIES2 NVARCHAR(MAX)
	DECLARE @RELATEDITEMS NVARCHAR(MAX)
	DECLARE @RELATEDORGANIZATIONS NVARCHAR(MAX)
	DECLARE @SYSTEMDETAILS NVARCHAR(MAX)
	DECLARE @ACCESSRESTRICTIONS NVARCHAR(MAX)
	DECLARE @AIC BIGINT
	DECLARE @ACTIVITY TABLE (ID BIGINT)
	--END -> DECLARING VARIABLES


	BEGIN TRANSACTION @TR_CREATE_ACTIVITY

	--INSERTING JSON ARRAY TO TEMP TABLE
	SELECT * INTO #PARSED FROM OPENJSON(@JSON)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO ACTIVITYDETAILS TABLE
	SET @ACTIVITYINFORMATION = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'activityInformation')
	INSERT INTO [dbo].[ActivityInformation](TypeofActivity, MajorClassification, MinorClassification, DescriptionOfTheActivity, StartDateTime, EndDateTime, Place, Country, AdministrativeDistrict, PoliceStation,Attendance, OutCome,GridLocationCode,GridRefName)
	OUTPUT INSERTED.AIC INTO @ACTIVITY
	SELECT * FROM OPENJSON(@ACTIVITYINFORMATION)
	WITH(
		TypeofActivity NVARCHAR(MAX) '$.typeOfActivity',
		MajorClassification NVARCHAR(MAX) '$.majorClassification',
		MinorClassification NVARCHAR(MAX) '$.minorClassification',
		DescriptionOfTheActivity NVARCHAR(MAX) '$.descriptionOfTheActivity',
		StartDateTime DATETIME '$.startDateTime',
		EndDateTime DATETIME '$.endDateTime',
		Place NVARCHAR(MAX) '$.place',
		Country NVARCHAR(MAX) '$.country',
		AdministrativeDistrict NVARCHAR(MAX) '$.administrativeDistrict',
		PoliceStation NVARCHAR(MAX) '$.policeStation',
		Attendance NVARCHAR(MAX) '$.attendance',
	    OutCome NVARCHAR(MAX) '$.outCome',
		GridLocationCode NVARCHAR(MAX) '$.gridLocationCode',
		GridRefName NVARCHAR(MAX) '$.gridRefName'
	)

	SET @AIC = (SELECT TOP 1 ID FROM @ACTIVITY)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO ACTIVEORGANIZERS TABLE
	SET @ACTIVEORGANIZERS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'activeOrganizers')
	INSERT INTO [dbo].[ActiveOrganizers](AIC,PIC)
	SELECT @AIC,* FROM OPENJSON(@ACTIVEORGANIZERS)
	WITH(
		PIC BIGINT '$.pic'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO AVAILABLECDS TABLE
	SET @AVAILABLECDS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'availableCDs')
	INSERT INTO [dbo].[AvailableCDs](AIC, Category,ReferenceNo)
	SELECT @AIC,* FROM OPENJSON(@AVAILABLECDS)
	WITH(
		Category NVARCHAR(MAX) '$.category',
		ReferenceNo NVARCHAR(MAX) '$.referenceNo'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO DETAILSOFSUSPECT TABLE
	SET @DETAILSOFSUSPECT = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'detailsOfSuspects')
	INSERT INTO [dbo].[DetailOfSuspect](AIC, PIC,[Status])
	SELECT @AIC,* FROM OPENJSON(@DETAILSOFSUSPECT)
	WITH(
		PIC BIGINT '$.pic',
		[Status] NVARCHAR(MAX) '$.status'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO DETAILSOFINSTRUCTORS TABLE
	SET @DETAILSOFINSTRUCTORS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'detailsOfInstructors')
	INSERT INTO [dbo].[DetailsOfInstructors](AIC, PIC, Country)
	SELECT @AIC,* FROM OPENJSON(@DETAILSOFINSTRUCTORS)
	WITH(
		PIC BIGINT '$.pic',
		Country NVARCHAR(MAX) '$.country'
		--Number NVARCHAR(MAX) '$.number'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO DETAILSOFLOCALCONTACTS TABLE
	SET @DETAILSOFLOCALCONTACTS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'detailsOfLocalContacts')
	INSERT INTO [dbo].[DetailsOfLocalContacts](AIC, PIC)
	SELECT @AIC,* FROM OPENJSON(@DETAILSOFLOCALCONTACTS)
	WITH(
		PIC BIGINT '$.pic'
	)

	----GET THE DATA FROM TEMP TABLE & INSERTING TO DETAILSOFVICTIMS TABLE
	--SET @DETAILSOFVICTIMS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'detailsOfVictims')
	--INSERT INTO [dbo].[DetailsOfVictims](AIC,PIC, Name, Category, Race,[Rank],NativePlace,[Status],Organization)
	--SELECT @AIC,
	--	   IIF(PIC = 0,NULL,PIC)'PIC',
	--      [Name],Category,Race,[Rank],NativePlace,[Status],Organization
	--  FROM OPENJSON(@DETAILSOFVICTIMS)
	--  WITH (
	--		PIC BIGINT '$.pic',
	--		Name NVARCHAR(MAX) '$.name',
	--		Category NVARCHAR(MAX) '$.category',
	--		Race NVARCHAR(MAX) '$.race',
	--		[Rank] NVARCHAR(MAX) '$.rank',
	--		NativePlace NVARCHAR(MAX) '$.nativePlace',
	--		[Status] NVARCHAR(MAX) '$.status',
	--		Organization NVARCHAR(MAX) '$.organization'
	--       )


		   --GET THE DATA FROM TEMP TABLE & INSERTING TO DETAILSOFVICTIMS TABLE
	SET @DETAILSOFVICTIMS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'detailsOfVictims')
	INSERT INTO [dbo].[DetailsOfVictims](AIC,PIC, Name, Category, Race,[Rank],NativePlace,[Status],Organization)
	SELECT @AIC,* FROM OPENJSON(@DETAILSOFVICTIMS)
	WITH(
		PIC BIGINT '$.pic',
		Name NVARCHAR(MAX) '$.name',
		Category NVARCHAR(MAX) '$.category',
		Race NVARCHAR(MAX) '$.race',
		[Rank] NVARCHAR(MAX) '$.rank',
		NativePlace NVARCHAR(MAX) '$.nativePlace',
		[Status] NVARCHAR(MAX) '$.status',
		Organization NVARCHAR(MAX) '$.organization'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO FILEREFERENCES TABLE
	SET @FILEREFERENCES = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'fileReferences')
	INSERT INTO [dbo].[FileReferences](AIC, FileReference)
	SELECT @AIC,* FROM OPENJSON(@FILEREFERENCES)
	WITH(
		FileReference NVARCHAR(MAX) '$.fileReference'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO INCIDENTS TABLE
	SET @INCIDENTS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'incidents')
	INSERT INTO [dbo].[Incidents](AIC, Incident)
	SELECT @AIC,* FROM OPENJSON(@INCIDENTS)
	WITH(
		Incident NVARCHAR(MAX) '$.incident'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO INSTITUTIONSAFFECTED TABLE
	SET @INSTITUTIONSAFFECTED = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'institutionsAffecteds')
	INSERT INTO [dbo].[InstitutionsAffected](AIC, NameofInstitution, MajorType, MinorType, HowAffected, Place)
	SELECT @AIC,* FROM OPENJSON(@INSTITUTIONSAFFECTED)
	WITH(
		NameofInstitution NVARCHAR(MAX) '$.nameofInstitution',
		MajorType NVARCHAR(MAX) '$.majorType',
		MinorType NVARCHAR(MAX) '$.minorType',
		HowAffected NVARCHAR(MAX) '$.howAffected',
		Place NVARCHAR(MAX) '$.place'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO ITEMSDISMISS TABLE
	SET @ITEMSDISMISS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'itemsDismisseds')
	INSERT INTO [dbo].[ItemsDismiss](AIC, IIC, Category, [Description],Number)
	SELECT @AIC,* FROM OPENJSON(@ITEMSDISMISS)
	WITH(
		IIC BIGINT '$.iic',
		Category NVARCHAR(MAX) '$.category',
		[Description] NVARCHAR(MAX) '$.description',
		Number NVARCHAR(MAX) '$.number'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO ITEMSUSED TABLE
	SET @ITEMSUSED = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'itemsUseds')
	INSERT INTO [dbo].[ItemsUsed](AIC, IIC, MajorType, MinorType, Number, Description)
	SELECT @AIC,* FROM OPENJSON(@ITEMSUSED)
	WITH(
		IIC BIGINT '$.iic',
		MajorType NVARCHAR(MAX) '$.majorType',
		MinorType NVARCHAR(MAX) '$.minorType',
		Number NVARCHAR(MAX) '$.number',
		Description NVARCHAR(MAX) '$.description'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO MAINSPEAKERS TABLE
	SET @MAINSPEAKERS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'mainSpeakers')
	INSERT INTO [dbo].[MainSpeakers](AIC, PIC,[Name])
	SELECT @AIC,* FROM OPENJSON(@MAINSPEAKERS)
	WITH(
		PIC BIGINT '$.pic',
		[Name] NVARCHAR(MAX) '$.name'
		
	)

		--GET THE DATA FROM TEMP TABLE & INSERTING TO MODUSOPERANDI TABLE
	SET @MODUSOPERANDI = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'modusOperandi')
	INSERT INTO [dbo].[ModusOperandi](AIC, ModusOperandi)
	SELECT @AIC,* FROM OPENJSON(@MODUSOPERANDI)
	WITH(
		--AIC BIGINT '$.aic',
		ModusOperandi NVARCHAR(MAX) '$.modusOperandi'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO NARRATIVEINFORMATION TABLE
	SET @NARRATIVEINFORMATION = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'narrativeInformations')
	INSERT INTO [dbo].[NarrativeInformation](AIC, [Date], Information, FileReferenceNo)
	SELECT @AIC,* FROM OPENJSON(@NARRATIVEINFORMATION)
	WITH(
		[Date] DATETIME '$.date',
		Information NVARCHAR(MAX) '$.information',
		FileReferenceNo NVARCHAR(MAX) '$.fileReferenceNo'
	)
	
	--GET THE DATA FROM TEMP TABLE & INSERTING TO NOOFINSTRUCTORS TABLE
	SET @NOOFINSTRUCTORS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'noOfInstructors')
	INSERT INTO [dbo].[NoOfInstructors](AIC, Country, Number)
	SELECT @AIC,* FROM OPENJSON(@NOOFINSTRUCTORS)
	WITH(
		Country NVARCHAR(MAX) '$.country',
		Number NVARCHAR(5) '$.number'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO NOOFPERSONSPARTICIPATED TABLE
	SET @NOOFPERSONSPARTICIPATED = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'noOfPersonsParticipateds')
	INSERT INTO [dbo].[NoOfPersonsParticipated](AIC, [Date], Number,[Category])
	SELECT @AIC,* FROM OPENJSON(@NOOFPERSONSPARTICIPATED)
	WITH(
		[Date] DATE '$.date',
		Number NVARCHAR(MAX) '$.number',
		[Category] NVARCHAR(MAX) '$.category'
	)


	--GET THE DATA FROM TEMP TABLE & INSERTING TO No Of Victims TABLE
	SET @NOOFPERSONSPARTICIPATED = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'noOfVictims')
	INSERT INTO [dbo].[NoOfVictims](AIC, Category, Race,[Status],Number,Organization)
	SELECT @AIC,* FROM OPENJSON(@NOOFPERSONSPARTICIPATED)
	WITH(
		
		Category NVARCHAR(MAX) '$.category',
		Race NVARCHAR(MAX) '$.race',
		[Status] NVARCHAR(MAX) '$.status',
		Number NVARCHAR(MAX) '$.number',
		Organization NVARCHAR(MAX) '$.organization'
	)


	--GET THE DATA FROM TEMP TABLE & INSERTING TO PHOTOGRAPHS TABLE
	SET @PHOTOGRAPHS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'photographs')
	INSERT INTO [dbo].[Photographs](AIC, Path, AddedDate)
	SELECT @AIC,* FROM OPENJSON(@PHOTOGRAPHS)
	WITH(
		
		Path NVARCHAR(MAX) '$.path',
		AddedDate DATE '$.addedDate'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO PRESIDEDOVERBY TABLE
	SET @PRESIDEDOVERBY = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'presidedOverBys')
	INSERT INTO [dbo].[PresidedOverBy](AIC, PIC)
	SELECT @AIC,* FROM OPENJSON(@PRESIDEDOVERBY)
	WITH(
		PIC BIGINT '$.pic'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO RELATEDACTIVITIES TABLE
	SET @RELATEDACTIVITIES = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'relatedActivities')
	INSERT INTO [dbo].[RelatedActivities](AIC, [RelatedActivity(AIC)])
	SELECT @AIC,* FROM OPENJSON(@RELATEDACTIVITIES)
	WITH(
		[RelatedActivity(AIC)] BIGINT '$.relatedActivityAIC'
	)


	--GET THE DATA FROM TEMP TABLE & INSERTING TO RELATEDORGANIZATIONS TABLE
	SET @RELATEDORGANIZATIONS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'relatedOrganizations')
	INSERT INTO [dbo].[RelatedOrganization](AIC, OIC, OrganizationCatagory)
	SELECT @AIC,* FROM OPENJSON(@RELATEDORGANIZATIONS)
	WITH(
		OIC BIGINT '$.oic',
		OrganizationCatagory NVARCHAR(MAX) '$.organizationCatagory'
	)

	--GET THE DATA FROM TEMP TABLE & INSERTING TO SYSTEMDETAILS TABLE
	SET @SYSTEMDETAILS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'systemDetails')
	INSERT INTO [dbo].[SystemDetails](AIC, EnteredUserName, LastModifiedUserName,  DeskTarget, [Subject], EnteredDate)
	SELECT @AIC,*,getdate() FROM OPENJSON(@SYSTEMDETAILS)
	WITH(
		EnteredUserName NVARCHAR(MAX) '$.enteredUserName',
		LastModifiedUserName NVARCHAR(MAX) '$.lastModifiedUserName',
		DeskTarget NVARCHAR(MAX) '$.deskTarget',
		Subject NVARCHAR(MAX) '$.subject'
	)


	SET @ACCESSRESTRICTIONS = (SELECT [VALUE] FROM #PARSED WHERE [KEY] = 'rolewiseAccessRestrictions')
	INSERT INTO [dbo].[DirectAndRoleWiseAccessRestrictions](AIC,DirectorOnly,DeskOfficerOnly)
	--SELECT * FROM DirectAndRoleWiseAccessRestrictions
	SELECT @AIC,* FROM OPENJSON(@ACCESSRESTRICTIONS)
	WITH(
		DirectorOnly bit '$.directorOnly',
		DeskOfficerOnly bit '$.deskOfficerOnly'
	)

	
	EXEC [dbo].[UPDATE_INFERENCE_RELATIONSHIPS] @AIC
	SELECT @AIC AS 'AIC'
	COMMIT TRANSACTION @TR_CREATE_ACTIVITY

END

