USE [SIS_Organization]
GO

/****** Object:  StoredProcedure [dbo].[SP_UPDATE_ORGANIZATION_RELATED_PERSONS]    Script Date: 19/06/2023 09:23:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_UPDATE_ORGANIZATION_RELATED_PERSONS] @JSON NVARCHAR(MAX) 
	
AS
BEGIN
--DECLARE TEMP TABLE ACCORGING TO TARGET
	DECLARE @TEMP TABLE(
		[ID] [bigint] NULL,
		[OIC] [bigint] NULL,
		[PIC] [bigint] NULL
	);

INSERT INTO @TEMP
	SELECT A.*
	FROM OPENJSON(@JSON) WITH (
	   _json nvarchar(max) '$' AS JSON
	) AS i
	CROSS APPLY OPENJSON(i._json) WITH (
		[ID] [bigint] '$.id',
		[OIC] [bigint] '$.oic',
		[PIC] [bigint] '$.pic'
	) A;

	--UPDATE OR MERGE TABLES
	MERGE [dbo].[RelatedPersons] ORI
	USING @TEMP TEMP
	ON (ORI.OIC = TEMP.OIC AND ORI.[PIC] = TEMP.[PIC])
	WHEN NOT MATCHED BY TARGET THEN
		INSERT ([OIC],[PIC])
		VALUES(TEMP.[OIC],TEMP.[PIC]);

	--WHEN NOT MATCHED BY SOURCE AND ORI.[OIC] = (SELECT TOP(1) [IIC] FROM @TEMP) THEN
	--	DELETE;
	--DELETE TEMP DATA
	DELETE FROM @TEMP;
END
GO


